#!/bin/bash

VERSION=1.0.0
HOME_GITHUB=$HOME/.gitchu

install() {
    # this function will make a folder to manager configs files
    mkdir -p $HOME_GITHUB
}

case "$1" in
--install)
    install
    ;;
*)
    install
    ;;
esac
